=== fabb/Stream-Graph/datasets.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="datasets.xsd" 
xmlns="datasets.xsd" elementFormDefault="qualified">
  <xs:element name="datasets">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string" />
        <xs:element name="x_axis" type="xs:string" />
        <xs:element name="y_axis" type="xs:string" />
        <xs:element name="dataset" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string" />
              <xs:element name="point" maxOccurs="unbounded" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="x_value" type="xs:string" />
                    <xs:element name="y_value" type="xs:integer" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>    
  </xs:element>
</xs:schema>

=== fabb/Stream-Graph/streamgraph_inskriptionen.xml
<?xml version='1.0' encoding='utf-8'?>
<!--
Barbara Csarman, Fabian Ehrentraud, 2011
-->
<datasets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datasets.xsd">
  <title>Inskribierte Studien pro Studienrichtung (inklusive Mitbeleger-Studien)</title>
  <x_axis>Semester</x_axis>
  <y_axis>Inskribierte Studien</y_axis>
  <dataset>
    <title>700 - Maschinenbau - Bachelorstudium</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>257</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>286</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>493</y_value>
    </point>
    <point>
      <x_value>2008S</x_value>
      <y_value>485</y_value>
    </point>
    <point>
      <x_value>2008W</x_value>
      <y_value>646</y_value>
    </point>
    <point>
      <x_value>2009S</x_value>
      <y_value>649</y_value>
    </point>
    <point>
      <x_value>2009W</x_value>
      <y_value>891</y_value>
    </point>
    <point>
      <x_value>2010S</x_value>
      <y_value>851</y_value>
    </point>
    <point>
      <x_value>2010W</x_value>
      <y_value>1030</y_value>
    </point>
    <point>
      <x_value>2011S</x_value>
      <y_value>955</y_value>
    </point>
  </dataset>
  <dataset>
    <title>MIT - Mitbelegerstudien - Masterstudium</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>142</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>152</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>135</y_value>
    </point>
    <point>
      <x_value>2008S</x_value>
      <y_value>157</y_value>
    </point>
    <point>
      <x_value>2008W</x_value>
      <y_value>189</y_value>
    </point>
    <point>
      <x_value>2009S</x_value>
      <y_value>186</y_value>
    </point>
    <point>
      <x_value>2009W</x_value>
      <y_value>190</y_value>
    </point>
    <point>
      <x_value>2010S</x_value>
      <y_value>209</y_value>
    </point>
    <point>
      <x_value>2010W</x_value>
      <y_value>196</y_value>
    </point>
    <point>
      <x_value>2011S</x_value>
      <y_value>137</y_value>
    </point>
  </dataset>
  <dataset>
    <title>860 - Technische Mathematik - Diplomstudium</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>841</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>775</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>717</y_value>
    </point>
    <point>
      <x_value>2008S</x_value>
      <y_value>672</y_value>
    </point>
    <point>
      <x_value>2008W</x_value>
      <y_value>639</y_value>
    </point>
    <point>
      <x_value>2009S</x_value>
      <y_value>479</y_value>
    </point>
    <point>
      <x_value>2009W</x_value>
      <y_value>406</y_value>
    </point>
    <point>
      <x_value>2010S</x_value>
      <y_value>360</y_value>
    </point>
    <point>
      <x_value>2010W</x_value>
      <y_value>311</y_value>
    </point>
    <point>
      <x_value>2011S</x_value>
      <y_value>224</y_value>
    </point>
  </dataset>
  <dataset>
    <title>705 - Biomedical Engineering - Masterstudium</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>0</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>0</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>0</y_value>
    </point>
    <point>
      <x_value>2008S</x_value>
      <y_value>0</y_value>
    </point>
    <point>
      <x_value>2008W</x_value>
      <y_value>39</y_value>
    </point>
    <point>
      <x_value>2009S</x_value>
      <y_value>54</y_value>
    </point>
    <point>
      <x_value>2009W</x_value>
      <y_value>89</y_value>
    </point>
    <point>
      <x_value>2010S</x_value>
      <y_value>92</y_value>
    </point>
    <point>
      <x_value>2010W</x_value>
      <y_value>130</y_value>
    </point>
    <point>
      <x_value>2011S</x_value>
      <y_value>129</y_value>
    </point>
  </dataset>
  <dataset>
    <title>800 - Technische Chemie - Bachelorstudium</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>148</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>164</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>288</y_value>
    </point>
    <point>
      <x_value>2008S</x_value>
      <y_value>268</y_value>
    </point>
    <point>
      <x_value>2008W</x_value>
      <y_value>403</y_value>
    </point>
    <point>
      <x_value>2009S</x_value>
      <y_value>409</y_value>
    </point>
    <point>
      <x_value>2009W</x_value>
      <y_value>516</y_value>
    </point>
    <point>
      <x_value>2010S</x_value>
      <y_value>496</y_value>
    </point>
    <point>
      <x_value>2010W</x_value>
      <y_value>640</y_value>
    </point>
    <point>
      <x_value>2011S</x_value>
      <y_value>578</y_value>
    </point>
  </dataset>
  <dataset>
    <title>610 - Bauingenieurwesen - Doktoratsstudium</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>137</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>142</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>145</y_value>
    </point>
    <point>
      <x_value>2008S</x_value>
      <y_value>142</y_value>
    </point>
    <point>
      <x_value>2008W</x_value>
      <y_value>139</y_value>
    </point>
    <point>
      <x_value>2009S</x_value>
      <y_value>197</y_value>
    </point>
    <point>
      <x_value>2009W</x_value>
      <y_value>200</y_value>
    </point>
    <point>
      <x_value>2010S</x_value>
      <y_value>208</y_value>
    </point>
    <point>
      <x_value>2010W</x_value>
      <y_value>217</y_value>
    </point>
    <point>
      <x_value>2011S</x_value>
      <y_value>190</y_value>
    </point>
  </dataset>
  <dataset>
    <title>660 - Vermessung und Geoinformation - Doktoratsstudium</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>33</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>37</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>44</y_value>
    </point>
    <point>
      <x_value>2008S</x_value>
      <y_value>42</y_value>
    </point>
    <point>
      <x_value>2008W</x_value>
      <y_value>42</y_value>
    </point>
    <point>
      <x_value>2009S</x_value>
      <y_value>49</y_value>
    </point>
    <point>
      <x_value>2009W</x_value>
      <y_value>47</y_value>
    </point>
    <point>
      <x_value>2010S</x_value>
      <y_value>47</y_value>
    </point>
    <point>
      <x_value>2010W</x_value>
      <y_value>53</y_value>
    </point>
    <point>
      <x_value>2011S</x_value>
      <y_value>48</y_value>
    </point>
  </dataset>
  <dataset>
    <title>MIT - Mitbelegerstudien - Ausserordentliches Studium</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>3</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>4</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>3</y_value>
    </point>
    <point>
      <x_value>2008S</x_value>
      <y_value>4</y_value>
    </point>
    <point>
      <x_value>2008W</x_value>
      <y_value>8</y_value>
    </point>
    <point>
      <x_value>2009S</x_value>
      <y_value>8</y_value>
    </point>
    <point>
      <x_value>2009W</x_value>
      <y_value>6</y_value>
    </point>
    <point>
      <x_value>2010S</x_value>
      <y_value>3</y_value>
    </point>
    <point>
      <x_value>2010W</x_value>
      <y_value>3</y_value>
    </point>
    <point>
      <x_value>2011S</x_value>
      <y_value>1</y_value>
    </point>
  </dataset>
  <dataset>
    <title>175 - Wirtschaftsinformatik - Masterstudium</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>265</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>277</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>296</y_value>
    </point>
    <point>
      <x_value>2008S</x_value>
      <y_value>294</y_value>
    </point>
    <point>
      <x_value>2008W</x_value>
      <y_value>304</y_value>
    </point>
    <point>
      <x_value>2009S</x_value>
      <y_value>310</y_value>
    </point>
    <point>
      <x_value>2009W</x_value>
      <y_value>331</y_value>
    </point>
    <point>
      <x_value>2010S</x_value>
      <y_value>339</y_value>
    </point>
    <point>
      <x_value>2010W</x_value>
      <y_value>332</y_value>
    </point>
    <point>
      <x_value>2011S</x_value>
      <y_value>285</y_value>
    </point>
  </dataset>
  <dataset>
    <title>MIT - Mitbelegerstudien - Lehramt</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>270</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>257</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>303</y_value>
    </point>
    <point>
      <x_value>2008S</x_value>
      <y_value>283</y_value>
    </point>
    <point>
      <x_value>2008W</x_value>
      <y_value>323</y_value>
    </point>
    <point>
      <x_value>2009S</x_value>
      <y_value>284</y_value>
    </point>
    <point>
      <x_value>2009W</x_value>
      <y_value>296</y_value>
    </point>
    <point>
      <x_value>2010S</x_value>
      <y_value>292</y_value>
    </point>
    <point>
      <x_value>2010W</x_value>
      <y_value>315</y_value>
    </point>
    <point>
      <x_value>2011S</x_value>
      <y_value>269</y_value>
    </point>
  </dataset>
  <dataset>
    <title>800 - Technische Chemie - Masterstudium</title>
    <point>
      <x_value>2006W</x_value>
      <y_value>3</y_value>
    </point>
    <point>
      <x_value>2007S</x_value>
      <y_value>6</y_value>
    </point>
    <point>
      <x_value>2007W</x_value>
      <y_value>20</y_value>
